# Generated by Django 5.2.5 on 2025-08-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.TextField(default="No description"),
        ),
    ]
